### PR TITLE
Adapt operator helm chart to v0.9.0

### PR DESCRIPTION
**Pull request by dashanji**
- Adapt the operator and apater helm chart to v0.9.0
- Add the related e2e test.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@kezhenxu94 We seem to face some incompatible changes when updated to 0.8. So, we should consider a new Helm release for bundled 0.8 SWCK.

**Review by hanahmily — APPROVED** [review]

**Comment by kezhenxu94** [comment]
> @kezhenxu94 We seem to face some incompatible changes when updated to 0.8. So, we should consider a new Helm release for bundled 0.8 SWCK.

I think we should consider releasing swck chart on its own instead of releasing all charts in this repo for nothing, the skywalking Helm Chart in this repo has no significant change since last release.

**Comment by wu-sheng** [comment]
You mean swck should have its own helm? Such as swck-helm?

**Comment by kezhenxu94** [comment]
> You mean swck should have its own helm? Such as swck-helm?

yes, currently [skywalking-helm](https://hub.docker.com/r/apache/skywalking-helm/tags) is only for skywalking-helm (OAP/UI), it's nothing related to swck at all, meaning swck users have to download source code to install

**Comment by wu-sheng** [comment]
@dashanji @hanahmily What do you think? Should we have a thing called swck-helm to guide users?

**Comment by dashanji** [comment]
> Should we have a thing called swck-helm to guide users?

Agree.

**Comment by wu-sheng** [comment]
@dashanji If we have an agreement, let's start a proposal to create `skywalking-swck-helm` repository to host this part of code and release it?

**Comment by dashanji** [comment]
> @dashanji If we have an agreement, let's start a proposal to create `skywalking-swck-helm` repository to host this part of code and release it?

No problem, but I don't know how to write the proposal. Is there a guide available?

**Comment by wu-sheng** [comment]
It is easy, aa you are a member of PMC, just need
- Which repository is proposed to create
- Background and why you need this

**Comment by dashanji** [comment]
> It is easy, aa you are a member of PMC, just need
> - Which repository is proposed to create
> - Background and why you need this

Thanks for the detail. One more question，where do I need to send the proposal？

**Comment by wu-sheng** [comment]
dev@skywalking.apache.org

**Comment by wu-sheng** [comment]
@dashanji Do you plan to ask for that after May public holiday?

**Comment by dashanji** [comment]
> @dashanji Do you plan to ask for that after May public holiday?

Yes.

**Pull request merged**
